/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppointmentCalendar: typeof import('./src/components/AppointmentCalendar.vue')['default']
    AppointmentForm: typeof import('./src/components/appointments/AppointmentForm.vue')['default']
    AppointmentFormModal: typeof import('./src/components/appointments/AppointmentFormModal.vue')['default']
    EmergencyContactForm: typeof import('./src/components/patients/EmergencyContactForm.vue')['default']
    IHeroiconsArrowLeft20Solid: typeof import('~icons/heroicons/arrow-left20-solid')['default']
    IHeroiconsArrowLeftEndOnRectangle20Solid: typeof import('~icons/heroicons/arrow-left-end-on-rectangle20-solid')['default']
    IHeroiconsArrowRightStartOnRectangle20Solid: typeof import('~icons/heroicons/arrow-right-start-on-rectangle20-solid')['default']
    IHeroiconsBars3: typeof import('~icons/heroicons/bars3')['default']
    IHeroiconsBriefcase20Solid: typeof import('~icons/heroicons/briefcase20-solid')['default']
    IHeroiconsCalendarDays20Solid: typeof import('~icons/heroicons/calendar-days20-solid')['default']
    IHeroiconsChartPie20Solid: typeof import('~icons/heroicons/chart-pie20-solid')['default']
    IHeroiconsChevronLeft20Solid: typeof import('~icons/heroicons/chevron-left20-solid')['default']
    IHeroiconsChevronRight20Solid: typeof import('~icons/heroicons/chevron-right20-solid')['default']
    IHeroiconsClock20Solid: typeof import('~icons/heroicons/clock20-solid')['default']
    IHeroiconsEye20Solid: typeof import('~icons/heroicons/eye20-solid')['default']
    IHeroiconsEyeSlash20Solid: typeof import('~icons/heroicons/eye-slash20-solid')['default']
    IHeroiconsUserGroup20Solid: typeof import('~icons/heroicons/user-group20-solid')['default']
    IHeroiconsXMark20Solid: typeof import('~icons/heroicons/x-mark20-solid')['default']
    LanguageSwitcher: typeof import('./src/components/LanguageSwitcher.vue')['default']
    PaymentForm: typeof import('./src/components/appointments/PaymentForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpecialtyForm: typeof import('./src/components/specialties/SpecialtyForm.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheSidebar: typeof import('./src/components/TheSidebar.vue')['default']
  }
}
