repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: mixed-line-ending
        args: ["--fix=lf"]
-   repo: local
    hooks:
    -   id: frontend-lint-format
        name: Frontend Lint & Format
        # entry: docker compose exec -T frontend sh -c 'npx eslint --fix "$@" && npx prettier --write "$@"'
        entry: >
            docker compose exec -T frontend sh -c '
                if [ $# -eq 0 ]; then
                    echo "No frontend files to lint/format. Skipping.";
                    exit 0;
                fi &&
                cd /app &&
                FILES=$(echo "$@" | xargs -n1 | sed "s|^frontend/||" | tr "\n" " ") &&
                echo "Linting/formatting frontend files: $FILES (from $@)" &&
                npx eslint --no-warn-ignored --fix $FILES &&
                npx prettier --ignore-unknown --write $FILES
            '
        language: system
        files: ^frontend/
        types: [file]
        pass_filenames: true
