services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - db_data:/app/db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:///db/${DATABASE_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - FERNET_KEY=${FERNET_KEY}
    healthcheck:
      test: [ "CMD-SHELL", "curl -s --max-time 5 localhost:8000 && exit 0 || exit 1" ]
      interval: 15s
      start_period: 5s
      timeout: 5s
      retries: 5
  tests:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    command: python -m pytest tests
    volumes:
      - ./backend:/app
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000
      - SECRET_KEY=${TEST_SECRET_KEY}
      - FERNET_KEY=${TEST_FERNET_KEY}
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
  node_modules:
