# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Install uv, the Python package installer
RUN pip install uv

# Copy and install the requirements
COPY ./requirements.txt /app/requirements.txt
RUN uv pip install --system --no-cache -r /app/requirements.txt

# Copy and install the test-specific dependencies
COPY ./requirements-test.txt /app/requirements-test.txt
RUN uv pip install --system --no-cache -r /app/requirements-test.txt

# Copy the rest of the backend application's source code from the host to the container
COPY . /app
