"""add_treatment_duration_logic_to_specialty

Revision ID: 0f43be752a1c
Revises: 3bfaa2173184
Create Date: 2025-08-19 17:37:37.406064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f43be752a1c'
down_revision: Union[str, Sequence[str], None] = '3bfaa2173184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specialties', sa.Column('treatment_duration_logic', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specialties', 'treatment_duration_logic')
    # ### end Alembic commands ###
