"""add_color_to_specialty

Revision ID: 31a1ec760e81
Revises: 5b6e2d0b822f
Create Date: 2025-08-21 13:09:50.235469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31a1ec760e81'
down_revision: Union[str, Sequence[str], None] = '5b6e2d0b822f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specialties', sa.Column('color', sa.String(length=9), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specialties', 'color')
    # ### end Alembic commands ###
