"""remove_unique_constraints_for_cell_and_email

Revision ID: 3bfaa2173184
Revises: d8c3a5306d2d
Create Date: 2025-08-13 20:02:47.520048

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3bfaa2173184"
down_revision: str | Sequence[str] | None = "d8c3a5306d2d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_patients_cellphone"), table_name="patients")
    op.create_index(op.f("ix_patients_cellphone"), "patients", ["cellphone"], unique=False)
    op.drop_index(op.f("ix_patients_email"), table_name="patients")
    op.create_index(op.f("ix_patients_email"), "patients", ["email"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_patients_email"), table_name="patients")
    op.create_index(op.f("ix_patients_email"), "patients", ["email"], unique=1)
    op.drop_index(op.f("ix_patients_cellphone"), table_name="patients")
    op.create_index(op.f("ix_patients_cellphone"), "patients", ["cellphone"], unique=1)
    # ### end Alembic commands ###
