"""add icon to specialty

Revision ID: da2c6665e95a
Revises: 31a1ec760e81
Create Date: 2025-08-26 23:44:00.651891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da2c6665e95a'
down_revision: Union[str, Sequence[str], None] = '31a1ec760e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specialties', sa.Column('icon', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specialties', 'icon')
    # ### end Alembic commands ###
