"""add is_active to payment_method

Revision ID: eb9df48a6336
Revises: da2c6665e95a
Create Date: 2025-08-27 14:53:51.002680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb9df48a6336'
down_revision: Union[str, Sequence[str], None] = 'da2c6665e95a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_methods', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_methods', 'is_active')
    # ### end Alembic commands ###
